name: CI-CD

on:
  push:
    branches:
      - task-11-flask-app-github

env:
  IMAGE_NAME: navaneetha4/flask-app
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: flask-cluster   # change this

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -----------------------------
      # Docker Login
      # -----------------------------
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------
      # Build Image
      # -----------------------------
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      # -----------------------------
      # Trivy Scan (Won't fail build)
      # -----------------------------
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: '0'

      # -----------------------------
      # Push Image
      # -----------------------------
      - name: Push Docker Image
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      # -----------------------------
      # Configure AWS Credentials
      # -----------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -----------------------------
      # Update kubeconfig for EKS
      # -----------------------------
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $EKS_CLUSTER_NAME \
            --region $AWS_REGION

      # -----------------------------
      # Verify Kubernetes Access
      # -----------------------------
      - name: Verify Cluster
        run: kubectl get nodes

      # -----------------------------
      # Setup Helm
      # -----------------------------
      - name: Setup Helm
        uses: azure/setup-helm@v3

      # -----------------------------
      # Deploy with Helm
      # -----------------------------
      - name: Deploy with Helm
        run: |
          helm upgrade --install flask-app ./helm/flask-app \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.sha }}
